export const TODOS_INIT = 'todos/init'
export const TODO_ADD = 'todo/add'
export const TODO_DELETE = 'todo/delete'
export const TODO_TOGGLE = 'todo/toggle'
export const TODO_EDIT = 'todo/edit'
export const TODOS_TOGGLE_ALL = 'todos/toggle-all'
export const TODOS_CLEAR_COMPLETED = 'todos/clear-completed'
